version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_DATABASE: "micro_net_hub"
      MYSQL_ROOT_PASSWORD: "root_1234"
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
